/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author ASUS
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJudul = new javax.swing.JLabel();
        labelBil1 = new javax.swing.JLabel();
        fieldBil1 = new javax.swing.JTextField();
        labelBil2 = new javax.swing.JLabel();
        fieldBil2 = new javax.swing.JTextField();
        buttonTambah = new javax.swing.JButton();
        buttonKurang = new javax.swing.JButton();
        buttonKali = new javax.swing.JButton();
        buttonBagi = new javax.swing.JButton();
        buttonMod = new javax.swing.JButton();
        textHasil = new javax.swing.JTextField();
        labelHasil = new javax.swing.JLabel();
        labelLingkaran = new javax.swing.JLabel();
        labelJari = new javax.swing.JLabel();
        fieldJari = new javax.swing.JTextField();
        buttonKelilingLingk = new javax.swing.JButton();
        buttonLuasLingk = new javax.swing.JButton();
        labelSegitiga = new javax.swing.JLabel();
        labelAlas = new javax.swing.JLabel();
        fieldAlas = new javax.swing.JTextField();
        buttonKelilingSegitiga = new javax.swing.JButton();
        buttonLuasSegitiga = new javax.swing.JButton();
        fieldTinggi = new javax.swing.JTextField();
        labelTinggi = new javax.swing.JLabel();
        labelSisi3 = new javax.swing.JLabel();
        fieldSisi3 = new javax.swing.JTextField();
        labelSisi2 = new javax.swing.JLabel();
        fieldSisi2 = new javax.swing.JTextField();
        labelPersegi = new javax.swing.JLabel();
        labelSisi = new javax.swing.JLabel();
        fieldSisi = new javax.swing.JTextField();
        buttonKelilingPersegi = new javax.swing.JButton();
        buttonLuasP = new javax.swing.JButton();
        labelPersegiPanjang = new javax.swing.JLabel();
        labelP = new javax.swing.JLabel();
        fieldP = new javax.swing.JTextField();
        buttonKelilingPP = new javax.swing.JButton();
        buttonLuasPP = new javax.swing.JButton();
        labelL = new javax.swing.JLabel();
        fieldL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJudul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelJudul.setText("Kalkulator Aritmatika");

        labelBil1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelBil1.setText("Bilangan 1");

        labelBil2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelBil2.setText("Bilangan 2");

        buttonTambah.setText("+");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonKurang.setText("-");
        buttonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKurangActionPerformed(evt);
            }
        });

        buttonKali.setText("*");
        buttonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKaliActionPerformed(evt);
            }
        });

        buttonBagi.setText("/");
        buttonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBagiActionPerformed(evt);
            }
        });

        buttonMod.setText("%");
        buttonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModActionPerformed(evt);
            }
        });

        textHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHasilActionPerformed(evt);
            }
        });

        labelHasil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelHasil.setText("Hasil");

        labelLingkaran.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelLingkaran.setText("Lingkaran");

        labelJari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelJari.setText("Jari- Jari");

        buttonKelilingLingk.setText("Keliling Lingkaran");
        buttonKelilingLingk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelilingLingkActionPerformed(evt);
            }
        });

        buttonLuasLingk.setText("Luas Lingkaran");
        buttonLuasLingk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuasLingkActionPerformed(evt);
            }
        });

        labelSegitiga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelSegitiga.setText("Segitiga");

        labelAlas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAlas.setText("Alas/Sisi 1");

        buttonKelilingSegitiga.setText("Keliling Segitiga");
        buttonKelilingSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelilingSegitigaActionPerformed(evt);
            }
        });

        buttonLuasSegitiga.setText("Luas Segitiga");
        buttonLuasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuasSegitigaActionPerformed(evt);
            }
        });

        labelTinggi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTinggi.setText("Tinggi");

        labelSisi3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSisi3.setText("Sisi 3");

        labelSisi2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSisi2.setText("Sisi 2");

        labelPersegi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPersegi.setText("Persegi");

        labelSisi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSisi.setText("Sisi");

        buttonKelilingPersegi.setText("Keliling Persegi");
        buttonKelilingPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelilingPersegiActionPerformed(evt);
            }
        });

        buttonLuasP.setText("Luas Persegi");
        buttonLuasP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuasPActionPerformed(evt);
            }
        });

        labelPersegiPanjang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPersegiPanjang.setText("Persegi Panjang");

        labelP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelP.setText("Panjang");

        buttonKelilingPP.setText("Keliling Persegi Panjang");
        buttonKelilingPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelilingPPActionPerformed(evt);
            }
        });

        buttonLuasPP.setText("Luas Persegi Panjang");
        buttonLuasPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLuasPPActionPerformed(evt);
            }
        });

        labelL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelL.setText("Lebar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldBil1)
                        .addComponent(fieldBil2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelBil2)
                                .addComponent(labelBil1))
                            .addGap(108, 108, 108)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonTambah)
                        .addGap(18, 18, 18)
                        .addComponent(buttonKurang)
                        .addGap(18, 18, 18)
                        .addComponent(buttonKali))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(buttonBagi)
                        .addGap(18, 18, 18)
                        .addComponent(buttonMod)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelJari)
                            .addComponent(fieldJari, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonKelilingLingk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonLuasLingk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelLingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAlas)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fieldTinggi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(fieldAlas, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(labelTinggi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelSisi2)
                                            .addComponent(fieldSisi2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelSisi3)
                                            .addComponent(fieldSisi3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(buttonKelilingSegitiga)))
                            .addComponent(buttonLuasSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonKelilingPersegi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonLuasP, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelSisi)
                                    .addGap(87, 87, 87))
                                .addComponent(labelPersegi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldSisi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(labelHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPersegiPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelP)
                    .addComponent(labelL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fieldP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonLuasPP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonKelilingPP, javax.swing.GroupLayout.Alignment.LEADING))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelJudul)
                                .addGap(18, 18, 18)
                                .addComponent(labelBil1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldBil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelBil2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldBil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonKali, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPersegiPanjang)
                                .addGap(18, 18, 18)
                                .addComponent(labelP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonKelilingPP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonLuasPP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelLingkaran)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelJari)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldJari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(buttonKelilingLingk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonLuasLingk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonLuasSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelSegitiga)
                                            .addGap(18, 18, 18)
                                            .addComponent(labelAlas)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fieldAlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(labelSisi2)
                                                .addComponent(labelSisi3))
                                            .addGap(26, 26, 26))
                                        .addComponent(fieldSisi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldSisi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelTinggi)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fieldTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(buttonKelilingSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPersegi)
                                .addGap(18, 18, 18)
                                .addComponent(labelSisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldSisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonKelilingPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonLuasP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(labelHasil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKurangActionPerformed
        // Pengurangan
        double bil1, bil2, hasil;
        
        bil1 = Double.parseDouble(this.fieldBil1.getText());
        bil2 = Double.parseDouble(this.fieldBil2.getText());
        
        hasil = bil1 - bil2;
        
        this.textHasil.setText("" +hasil);
    }//GEN-LAST:event_buttonKurangActionPerformed

    private void textHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHasilActionPerformed

    private void buttonLuasLingkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuasLingkActionPerformed
        // LUAS LINGKARAN
        final double pi= 3.14;
        double r,luasL;
        
        r = Double.parseDouble(this.fieldJari.getText());
        
        luasL = pi*r*r;
        
        this.textHasil.setText("" +luasL);
    }//GEN-LAST:event_buttonLuasLingkActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // Penjumlahan
        double bil1, bil2, hasil;
        
        bil1 = Double.parseDouble(this.fieldBil1.getText());
        bil2 = Double.parseDouble(this.fieldBil2.getText());
        
        hasil = bil1 + bil2;
        
        this.textHasil.setText("" +hasil);
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKaliActionPerformed
        // Perkalian
        double bil1, bil2, hasil;
        
        bil1 = Double.parseDouble(this.fieldBil1.getText());
        bil2 = Double.parseDouble(this.fieldBil2.getText());
        
        hasil = bil1 * bil2;
        
        this.textHasil.setText("" +hasil);
    }//GEN-LAST:event_buttonKaliActionPerformed

    private void buttonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBagiActionPerformed
        // Pembagian
        double bil1, bil2, hasil;
        
        bil1 = Double.parseDouble(this.fieldBil1.getText());
        bil2 = Double.parseDouble(this.fieldBil2.getText());
        
        hasil = bil1 / bil2;
        
        this.textHasil.setText("" +hasil);
    }//GEN-LAST:event_buttonBagiActionPerformed

    private void buttonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModActionPerformed
        // Hasil Bagi
        double bil1, bil2, hasil;
        
        bil1 = Double.parseDouble(this.fieldBil1.getText());
        bil2 = Double.parseDouble(this.fieldBil2.getText());
        
        hasil = bil1 % bil2;
        
        this.textHasil.setText("" +hasil);
    }//GEN-LAST:event_buttonModActionPerformed

    private void buttonLuasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuasSegitigaActionPerformed
        // LUAS Segitiga
        double a,t,luasS;
        
        a = Double.parseDouble(this.fieldAlas.getText());
       
        t = Double.parseDouble(this.fieldTinggi.getText());
        
        luasS = a*t/2;
        
        this.textHasil.setText("" +luasS);
    }//GEN-LAST:event_buttonLuasSegitigaActionPerformed

    private void buttonKelilingSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelilingSegitigaActionPerformed
        // KELILING Segitiga
        double a,s2,s3,kelS;
        
        a = Double.parseDouble(this.fieldAlas.getText());
       
        s2 = Double.parseDouble(this.fieldSisi2.getText());
        s3 = Double.parseDouble(this.fieldSisi3.getText());
        
        kelS = a+s2+s3;
        
        this.textHasil.setText("" +kelS);
    }//GEN-LAST:event_buttonKelilingSegitigaActionPerformed

    private void buttonLuasPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuasPActionPerformed
         // LUAS Persegi
        double s,luasP;
        
        s = Double.parseDouble(this.fieldSisi.getText());
       
        luasP = s*s;
        
        this.textHasil.setText("" +luasP);
    }//GEN-LAST:event_buttonLuasPActionPerformed

    private void buttonLuasPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLuasPPActionPerformed
        // KELILING Persegi Panjang
        double p,l, luasPP;
        
        p = Double.parseDouble(this.fieldP.getText());
        l = Double.parseDouble(this.fieldL.getText());
        luasPP = p*l;
        
        this.textHasil.setText("" +luasPP);
    }//GEN-LAST:event_buttonLuasPPActionPerformed

    private void buttonKelilingLingkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelilingLingkActionPerformed
        // KELILING LINGKARAN
        final double pi= 3.14;
        double r,kelL;
        
        r = Double.parseDouble(this.fieldJari.getText());
        
        kelL = 2*pi*r;
        
        this.textHasil.setText("" +kelL);
        
    }//GEN-LAST:event_buttonKelilingLingkActionPerformed

    private void buttonKelilingPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelilingPersegiActionPerformed
         // KELILING Persegi
        double s,kelP;
        
        s = Double.parseDouble(this.fieldSisi.getText());
       
        kelP = 4*s;
        
        this.textHasil.setText("" +kelP);
    }//GEN-LAST:event_buttonKelilingPersegiActionPerformed

    private void buttonKelilingPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelilingPPActionPerformed
        // KELILING Persegi Panjang
        double p,l, kelPP;
        
        p = Double.parseDouble(this.fieldP.getText());
        l = Double.parseDouble(this.fieldL.getText());
        kelPP = 2*p+2*l;
        
        this.textHasil.setText("" +kelPP);
    }//GEN-LAST:event_buttonKelilingPPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBagi;
    private javax.swing.JButton buttonKali;
    private javax.swing.JButton buttonKelilingLingk;
    private javax.swing.JButton buttonKelilingPP;
    private javax.swing.JButton buttonKelilingPersegi;
    private javax.swing.JButton buttonKelilingSegitiga;
    private javax.swing.JButton buttonKurang;
    private javax.swing.JButton buttonLuasLingk;
    private javax.swing.JButton buttonLuasP;
    private javax.swing.JButton buttonLuasPP;
    private javax.swing.JButton buttonLuasSegitiga;
    private javax.swing.JButton buttonMod;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JTextField fieldAlas;
    private javax.swing.JTextField fieldBil1;
    private javax.swing.JTextField fieldBil2;
    private javax.swing.JTextField fieldJari;
    private javax.swing.JTextField fieldL;
    private javax.swing.JTextField fieldP;
    private javax.swing.JTextField fieldSisi;
    private javax.swing.JTextField fieldSisi2;
    private javax.swing.JTextField fieldSisi3;
    private javax.swing.JTextField fieldTinggi;
    private javax.swing.JLabel labelAlas;
    private javax.swing.JLabel labelBil1;
    private javax.swing.JLabel labelBil2;
    private javax.swing.JLabel labelHasil;
    private javax.swing.JLabel labelJari;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelL;
    private javax.swing.JLabel labelLingkaran;
    private javax.swing.JLabel labelP;
    private javax.swing.JLabel labelPersegi;
    private javax.swing.JLabel labelPersegiPanjang;
    private javax.swing.JLabel labelSegitiga;
    private javax.swing.JLabel labelSisi;
    private javax.swing.JLabel labelSisi2;
    private javax.swing.JLabel labelSisi3;
    private javax.swing.JLabel labelTinggi;
    private javax.swing.JTextField textHasil;
    // End of variables declaration//GEN-END:variables
}
